  . = ALIGN(16); /* MPC5510 MPU requires 16 bytes alignment */
  __SEG_START_TASK_$TASK_NAME$_CONST_RGN = .;
  * (.Task_$TASK_NAME$SECCONST_32BIT)
  * (.Task_$TASK_NAME$SECCONST_16BIT)
  * (.Task_$TASK_NAME$SECCONST_8BIT)
  * (.Task_$TASK_NAME$SECCONST_BOOLEAN)
  * (.Task_$TASK_NAME$SECCONST_UNSPECIFIED)
  . = ALIGN(16);
  __SEG_END_TASK_$TASK_NAME$_CONST_RGN = . - 1;
  