#ifndef __REGISTERS_H__
#define __REGISTERS_H__

/* define can registers */
#define FRAME_REG_1   1
#define FRAME_REG_2   2
#define FRAME_REG_3   4
#define FRAME_REG_4   8
#define FRAME_REG_5   16
#define FRAME_REG_6   32
#define FILTER_REG_1  64
#define FILTER_REG_2  128
#define FILTER_REG_3  256
#define FILTER_REG_4  512
#define FILTER_REG_5  1024
#define FILTER_REG_6  2048
#define FILTER_REG_7  4096
#define FILTER_REG_8  8192
#define FILTER_REG_9  16384
#define FILTER_REG_10 32768
#define FILTER_REG_11 65536
#define FILTER_REG_12 131072
#define FILTER_REG_13 262144
#define FILTER_REG_14 524288
#define FILTER_REG_15 1048576
#define FILTER_REG_16 2097152

/* define can id */
#define CAN 0x1 << (16 + 6)

/* define can registers*/
#define CAN_FRAME_REG_1	  CAN | FRAME_REG_1
#define CAN_FRAME_REG_2	  CAN | FRAME_REG_2
#define CAN_FRAME_REG_3	  CAN | FRAME_REG_3
#define CAN_FRAME_REG_4	  CAN | FRAME_REG_4
#define CAN_FRAME_REG_5	  CAN | FRAME_REG_5
#define CAN_FRAME_REG_6	  CAN | FRAME_REG_6
#define CAN_FILTER_REG_1  CAN | FILTER_REG_1
#define CAN_FILTER_REG_2  CAN | FILTER_REG_2
#define CAN_FILTER_REG_3  CAN | FILTER_REG_3
#define CAN_FILTER_REG_4  CAN | FILTER_REG_4
#define CAN_FILTER_REG_5  CAN | FILTER_REG_5
#define CAN_FILTER_REG_6  CAN | FILTER_REG_6
#define CAN_FILTER_REG_7  CAN | FILTER_REG_7
#define CAN_FILTER_REG_8  CAN | FILTER_REG_8
#define CAN_FILTER_REG_9  CAN | FILTER_REG_9
#define CAN_FILTER_REG_10 CAN | FILTER_REG_10
#define CAN_FILTER_REG_11 CAN | FILTER_REG_11
#define CAN_FILTER_REG_12 CAN | FILTER_REG_12
#define CAN_FILTER_REG_13 CAN | FILTER_REG_13
#define CAN_FILTER_REG_14 CAN | FILTER_REG_14
#define CAN_FILTER_REG_15 CAN | FILTER_REG_15
#define CAN_FILTER_REG_16 CAN | FILTER_REG_16

#endif

