//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'goil_cpu_level_include.cpp'                      *
//                    Generated by version version 2.2.0                     *
//                       june 1st, 2011, at 14h33'7"                         *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*

#include "utilities/MF_MemoryControl.h"

//---------------------------------------------------------------------------*

#include "goil_cpu_level_include.h"

//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//              L L ( 1 )    P R O D U C T I O N    R U L E S                *
//                                                                           *
//---------------------------------------------------------------------------*

#define TERMINAL(t)     ((t)+1)
#define NONTERMINAL(nt) ((-nt)-1)
#define END_PRODUCTION  (0)

static const PMSInt16 gProductions [] = {
// At index 0 : <start>, in file 'goil_syntax.ggs', line 38
  NONTERMINAL (2) // <file>
, END_PRODUCTION
// At index 2 : <file>, in file 'goil_syntax.ggs', line 82
, NONTERMINAL (13) // <select_goil_5F_syntax_0>
, END_PRODUCTION
// At index 4 : <sign>, in file 'goil_syntax.ggs', line 93
, NONTERMINAL (14) // <select_goil_5F_syntax_1>
, END_PRODUCTION
// At index 6 : <description>, in file 'goil_syntax.ggs', line 107
, NONTERMINAL (15) // <select_goil_5F_syntax_2>
, END_PRODUCTION
// At index 8 : <OIL_version>, in file 'goil_syntax.ggs', line 118
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_OIL_5F_VERSION) // $OIL_VERSION$
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__3D_) // $=$
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_string) // $string$
, NONTERMINAL (4) // <description>
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__3B_) // $;$
, END_PRODUCTION
// At index 14 : <application_definition>, in file 'goil_syntax.ggs', line 125
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_CPU) // $CPU$
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_idf) // $idf$
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__7B_) // ${$
, NONTERMINAL (7) // <object_definition_list>
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__7D_) // $}$
, NONTERMINAL (4) // <description>
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__3B_) // $;$
, END_PRODUCTION
// At index 22 : <object_definition_list>, in file 'goil_syntax.ggs', line 134
, NONTERMINAL (16) // <select_goil_5F_syntax_3>
, END_PRODUCTION
// At index 24 : <boolean>, in file 'goil_syntax.ggs', line 172
, NONTERMINAL (17) // <select_goil_5F_syntax_4>
, END_PRODUCTION
// At index 26 : <oil_declaration_list>, in file 'goil_syntax.ggs', line 182
, NONTERMINAL (18) // <select_goil_5F_syntax_5>
, END_PRODUCTION
// At index 28 : <oil_declaration>, in file 'goil_syntax.ggs', line 192
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_idf) // $idf$
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__3D_) // $=$
, NONTERMINAL (19) // <select_goil_5F_syntax_6>
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__3B_) // $;$
, END_PRODUCTION
// At index 33 : <include_file_level>, in file 'goil_syntax.ggs', line 316
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_include) // $include$
, NONTERMINAL (23) // <select_goil_5F_syntax_10>
, END_PRODUCTION
// At index 36 : <include_cpu_level>, in file 'goil_syntax.ggs', line 328
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_include) // $include$
, NONTERMINAL (24) // <select_goil_5F_syntax_11>
, END_PRODUCTION
//---- Added productions from 'select' and 'repeat' instructions
// At index 39 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
, END_PRODUCTION
// At index 40 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
, NONTERMINAL (11) // <include_file_level>
, NONTERMINAL (13) // <select_goil_5F_syntax_0>
, END_PRODUCTION
// At index 43 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
, NONTERMINAL (5) // <OIL_version>
, NONTERMINAL (13) // <select_goil_5F_syntax_0>
, END_PRODUCTION
// At index 46 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
, NONTERMINAL (0) // <implementation_definition>
, NONTERMINAL (13) // <select_goil_5F_syntax_0>
, END_PRODUCTION
// At index 49 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
, NONTERMINAL (6) // <application_definition>
, NONTERMINAL (13) // <select_goil_5F_syntax_0>
, END_PRODUCTION
// At index 52 : <select_goil_5F_syntax_1>, in file 'goil_syntax.ggs', line 96
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__2D_) // $-$
, END_PRODUCTION
// At index 54 : <select_goil_5F_syntax_1>, in file 'goil_syntax.ggs', line 96
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__2B_) // $+$
, END_PRODUCTION
// At index 56 : <select_goil_5F_syntax_1>, in file 'goil_syntax.ggs', line 96
, END_PRODUCTION
// At index 57 : <select_goil_5F_syntax_2>, in file 'goil_syntax.ggs', line 109
, END_PRODUCTION
// At index 58 : <select_goil_5F_syntax_2>, in file 'goil_syntax.ggs', line 109
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__3A_) // $:$
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_string) // $string$
, END_PRODUCTION
// At index 61 : <select_goil_5F_syntax_3>, in file 'goil_syntax.ggs', line 136
, END_PRODUCTION
// At index 62 : <select_goil_5F_syntax_3>, in file 'goil_syntax.ggs', line 136
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_idf) // $idf$
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_idf) // $idf$
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__7B_) // ${$
, NONTERMINAL (9) // <oil_declaration_list>
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__7D_) // $}$
, NONTERMINAL (4) // <description>
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__3B_) // $;$
, NONTERMINAL (16) // <select_goil_5F_syntax_3>
, END_PRODUCTION
// At index 71 : <select_goil_5F_syntax_3>, in file 'goil_syntax.ggs', line 136
, NONTERMINAL (12) // <include_cpu_level>
, NONTERMINAL (16) // <select_goil_5F_syntax_3>
, END_PRODUCTION
// At index 74 : <select_goil_5F_syntax_4>, in file 'goil_syntax.ggs', line 174
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_TRUE) // $TRUE$
, END_PRODUCTION
// At index 76 : <select_goil_5F_syntax_4>, in file 'goil_syntax.ggs', line 174
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_FALSE) // $FALSE$
, END_PRODUCTION
// At index 78 : <select_goil_5F_syntax_5>, in file 'goil_syntax.ggs', line 187
, END_PRODUCTION
// At index 79 : <select_goil_5F_syntax_5>, in file 'goil_syntax.ggs', line 187
, NONTERMINAL (10) // <oil_declaration>
, NONTERMINAL (18) // <select_goil_5F_syntax_5>
, END_PRODUCTION
// At index 82 : <select_goil_5F_syntax_6>, in file 'goil_syntax.ggs', line 213
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_idf) // $idf$
, NONTERMINAL (20) // <select_goil_5F_syntax_7>
, END_PRODUCTION
// At index 85 : <select_goil_5F_syntax_6>, in file 'goil_syntax.ggs', line 213
, NONTERMINAL (3) // <sign>
, NONTERMINAL (21) // <select_goil_5F_syntax_8>
, END_PRODUCTION
// At index 88 : <select_goil_5F_syntax_6>, in file 'goil_syntax.ggs', line 213
, NONTERMINAL (8) // <boolean>
, NONTERMINAL (22) // <select_goil_5F_syntax_9>
, END_PRODUCTION
// At index 91 : <select_goil_5F_syntax_6>, in file 'goil_syntax.ggs', line 213
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_string) // $string$
, END_PRODUCTION
// At index 93 : <select_goil_5F_syntax_7>, in file 'goil_syntax.ggs', line 234
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__7B_) // ${$
, NONTERMINAL (9) // <oil_declaration_list>
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__7D_) // $}$
, END_PRODUCTION
// At index 97 : <select_goil_5F_syntax_7>, in file 'goil_syntax.ggs', line 234
, END_PRODUCTION
// At index 98 : <select_goil_5F_syntax_8>, in file 'goil_syntax.ggs', line 249
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_uint_5F_number) // $uint_number$
, END_PRODUCTION
// At index 100 : <select_goil_5F_syntax_8>, in file 'goil_syntax.ggs', line 249
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_float_5F_number) // $float_number$
, END_PRODUCTION
// At index 102 : <select_goil_5F_syntax_9>, in file 'goil_syntax.ggs', line 277
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__7B_) // ${$
, NONTERMINAL (9) // <oil_declaration_list>
, TERMINAL (C_Lexique_goil_5F_lexique::kToken__7D_) // $}$
, END_PRODUCTION
// At index 106 : <select_goil_5F_syntax_9>, in file 'goil_syntax.ggs', line 277
, END_PRODUCTION
// At index 107 : <select_goil_5F_syntax_10>, in file 'goil_syntax.ggs', line 320
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_g_5F_string) // $g_string$
, END_PRODUCTION
// At index 109 : <select_goil_5F_syntax_10>, in file 'goil_syntax.ggs', line 320
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_string) // $string$
, END_PRODUCTION
// At index 111 : <select_goil_5F_syntax_11>, in file 'goil_syntax.ggs', line 332
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_g_5F_string) // $g_string$
, END_PRODUCTION
// At index 113 : <select_goil_5F_syntax_11>, in file 'goil_syntax.ggs', line 332
, TERMINAL (C_Lexique_goil_5F_lexique::kToken_string) // $string$
, END_PRODUCTION
// At index 115 : <>, in file '.ggs', line 0
, NONTERMINAL (7) // <object_definition_list>
, END_PRODUCTION
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                     P R O D U C T I O N    N A M E S                      *
//                                                                           *
//---------------------------------------------------------------------------*

static const cProductionNameDescriptor gProductionNames [44] = {
 {"<start>", "goil_syntax", 0}, // at index 0
 {"<file>", "goil_syntax", 2}, // at index 1
 {"<sign>", "goil_syntax", 4}, // at index 2
 {"<description>", "goil_syntax", 6}, // at index 3
 {"<OIL_version>", "goil_syntax", 8}, // at index 4
 {"<application_definition>", "goil_syntax", 14}, // at index 5
 {"<object_definition_list>", "goil_syntax", 22}, // at index 6
 {"<boolean>", "goil_syntax", 24}, // at index 7
 {"<oil_declaration_list>", "goil_syntax", 26}, // at index 8
 {"<oil_declaration>", "goil_syntax", 28}, // at index 9
 {"<include_file_level>", "goil_syntax", 33}, // at index 10
 {"<include_cpu_level>", "goil_syntax", 36}, // at index 11
 {"<select_goil_5F_syntax_0>", "goil_syntax", 39}, // at index 12
 {"<select_goil_5F_syntax_0>", "goil_syntax", 40}, // at index 13
 {"<select_goil_5F_syntax_0>", "goil_syntax", 43}, // at index 14
 {"<select_goil_5F_syntax_0>", "goil_syntax", 46}, // at index 15
 {"<select_goil_5F_syntax_0>", "goil_syntax", 49}, // at index 16
 {"<select_goil_5F_syntax_1>", "goil_syntax", 52}, // at index 17
 {"<select_goil_5F_syntax_1>", "goil_syntax", 54}, // at index 18
 {"<select_goil_5F_syntax_1>", "goil_syntax", 56}, // at index 19
 {"<select_goil_5F_syntax_2>", "goil_syntax", 57}, // at index 20
 {"<select_goil_5F_syntax_2>", "goil_syntax", 58}, // at index 21
 {"<select_goil_5F_syntax_3>", "goil_syntax", 61}, // at index 22
 {"<select_goil_5F_syntax_3>", "goil_syntax", 62}, // at index 23
 {"<select_goil_5F_syntax_3>", "goil_syntax", 71}, // at index 24
 {"<select_goil_5F_syntax_4>", "goil_syntax", 74}, // at index 25
 {"<select_goil_5F_syntax_4>", "goil_syntax", 76}, // at index 26
 {"<select_goil_5F_syntax_5>", "goil_syntax", 78}, // at index 27
 {"<select_goil_5F_syntax_5>", "goil_syntax", 79}, // at index 28
 {"<select_goil_5F_syntax_6>", "goil_syntax", 82}, // at index 29
 {"<select_goil_5F_syntax_6>", "goil_syntax", 85}, // at index 30
 {"<select_goil_5F_syntax_6>", "goil_syntax", 88}, // at index 31
 {"<select_goil_5F_syntax_6>", "goil_syntax", 91}, // at index 32
 {"<select_goil_5F_syntax_7>", "goil_syntax", 93}, // at index 33
 {"<select_goil_5F_syntax_7>", "goil_syntax", 97}, // at index 34
 {"<select_goil_5F_syntax_8>", "goil_syntax", 98}, // at index 35
 {"<select_goil_5F_syntax_8>", "goil_syntax", 100}, // at index 36
 {"<select_goil_5F_syntax_9>", "goil_syntax", 102}, // at index 37
 {"<select_goil_5F_syntax_9>", "goil_syntax", 106}, // at index 38
 {"<select_goil_5F_syntax_10>", "goil_syntax", 107}, // at index 39
 {"<select_goil_5F_syntax_10>", "goil_syntax", 109}, // at index 40
 {"<select_goil_5F_syntax_11>", "goil_syntax", 111}, // at index 41
 {"<select_goil_5F_syntax_11>", "goil_syntax", 113}, // at index 42
 {"<>", "", 115} // at index 43
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//            L L ( 1 )    P R O D U C T I O N    I N D E X E S              *
//                                                                           *
//---------------------------------------------------------------------------*

static const PMSInt16 gProductionIndexes [44] = {
0, // index 0 : <start>, in file 'goil_syntax.ggs', line 38
2, // index 1 : <file>, in file 'goil_syntax.ggs', line 82
4, // index 2 : <sign>, in file 'goil_syntax.ggs', line 93
6, // index 3 : <description>, in file 'goil_syntax.ggs', line 107
8, // index 4 : <OIL_version>, in file 'goil_syntax.ggs', line 118
14, // index 5 : <application_definition>, in file 'goil_syntax.ggs', line 125
22, // index 6 : <object_definition_list>, in file 'goil_syntax.ggs', line 134
24, // index 7 : <boolean>, in file 'goil_syntax.ggs', line 172
26, // index 8 : <oil_declaration_list>, in file 'goil_syntax.ggs', line 182
28, // index 9 : <oil_declaration>, in file 'goil_syntax.ggs', line 192
33, // index 10 : <include_file_level>, in file 'goil_syntax.ggs', line 316
36, // index 11 : <include_cpu_level>, in file 'goil_syntax.ggs', line 328
39, // index 12 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
40, // index 13 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
43, // index 14 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
46, // index 15 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
49, // index 16 : <select_goil_5F_syntax_0>, in file 'goil_syntax.ggs', line 86
52, // index 17 : <select_goil_5F_syntax_1>, in file 'goil_syntax.ggs', line 96
54, // index 18 : <select_goil_5F_syntax_1>, in file 'goil_syntax.ggs', line 96
56, // index 19 : <select_goil_5F_syntax_1>, in file 'goil_syntax.ggs', line 96
57, // index 20 : <select_goil_5F_syntax_2>, in file 'goil_syntax.ggs', line 109
58, // index 21 : <select_goil_5F_syntax_2>, in file 'goil_syntax.ggs', line 109
61, // index 22 : <select_goil_5F_syntax_3>, in file 'goil_syntax.ggs', line 136
62, // index 23 : <select_goil_5F_syntax_3>, in file 'goil_syntax.ggs', line 136
71, // index 24 : <select_goil_5F_syntax_3>, in file 'goil_syntax.ggs', line 136
74, // index 25 : <select_goil_5F_syntax_4>, in file 'goil_syntax.ggs', line 174
76, // index 26 : <select_goil_5F_syntax_4>, in file 'goil_syntax.ggs', line 174
78, // index 27 : <select_goil_5F_syntax_5>, in file 'goil_syntax.ggs', line 187
79, // index 28 : <select_goil_5F_syntax_5>, in file 'goil_syntax.ggs', line 187
82, // index 29 : <select_goil_5F_syntax_6>, in file 'goil_syntax.ggs', line 213
85, // index 30 : <select_goil_5F_syntax_6>, in file 'goil_syntax.ggs', line 213
88, // index 31 : <select_goil_5F_syntax_6>, in file 'goil_syntax.ggs', line 213
91, // index 32 : <select_goil_5F_syntax_6>, in file 'goil_syntax.ggs', line 213
93, // index 33 : <select_goil_5F_syntax_7>, in file 'goil_syntax.ggs', line 234
97, // index 34 : <select_goil_5F_syntax_7>, in file 'goil_syntax.ggs', line 234
98, // index 35 : <select_goil_5F_syntax_8>, in file 'goil_syntax.ggs', line 249
100, // index 36 : <select_goil_5F_syntax_8>, in file 'goil_syntax.ggs', line 249
102, // index 37 : <select_goil_5F_syntax_9>, in file 'goil_syntax.ggs', line 277
106, // index 38 : <select_goil_5F_syntax_9>, in file 'goil_syntax.ggs', line 277
107, // index 39 : <select_goil_5F_syntax_10>, in file 'goil_syntax.ggs', line 320
109, // index 40 : <select_goil_5F_syntax_10>, in file 'goil_syntax.ggs', line 320
111, // index 41 : <select_goil_5F_syntax_11>, in file 'goil_syntax.ggs', line 332
113, // index 42 : <select_goil_5F_syntax_11>, in file 'goil_syntax.ggs', line 332
115 // index 43 : <>, in file '.ggs', line 0
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//      L L ( 1 )    F I R S T    P R O D U C T I O N    I N D E X E S       *
//                                                                           *
//---------------------------------------------------------------------------*

static const PMSInt16 gFirstProductionIndexes [27] = {
0, // at 0 : <implementation_definition>
0, // at 1 : <start>
1, // at 2 : <file>
2, // at 3 : <sign>
3, // at 4 : <description>
4, // at 5 : <OIL_version>
5, // at 6 : <application_definition>
6, // at 7 : <object_definition_list>
7, // at 8 : <boolean>
8, // at 9 : <oil_declaration_list>
9, // at 10 : <oil_declaration>
10, // at 11 : <include_file_level>
11, // at 12 : <include_cpu_level>
12, // at 13 : <select_goil_5F_syntax_0>
17, // at 14 : <select_goil_5F_syntax_1>
20, // at 15 : <select_goil_5F_syntax_2>
22, // at 16 : <select_goil_5F_syntax_3>
25, // at 17 : <select_goil_5F_syntax_4>
27, // at 18 : <select_goil_5F_syntax_5>
29, // at 19 : <select_goil_5F_syntax_6>
33, // at 20 : <select_goil_5F_syntax_7>
35, // at 21 : <select_goil_5F_syntax_8>
37, // at 22 : <select_goil_5F_syntax_9>
39, // at 23 : <select_goil_5F_syntax_10>
41, // at 24 : <select_goil_5F_syntax_11>
43, // at 25 : <>
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//               L L ( 1 )    D E C I S I O N    T A B L E S                 *
//                                                                           *
//---------------------------------------------------------------------------*

static const PMSInt16 gDecision [] = {
// At index 0 : <implementation_definition> no production
// At index 0 : <start> only one production, no choice
  -1,
// At index 1 : <file> only one production, no choice
  -1,
// At index 2 : <sign> only one production, no choice
  -1,
// At index 3 : <description> only one production, no choice
  -1,
// At index 4 : <OIL_version> only one production, no choice
  -1,
// At index 5 : <application_definition> only one production, no choice
  -1,
// At index 6 : <object_definition_list> only one production, no choice
  -1,
// At index 7 : <boolean> only one production, no choice
  -1,
// At index 8 : <oil_declaration_list> only one production, no choice
  -1,
// At index 9 : <oil_declaration> only one production, no choice
  -1,
// At index 10 : <include_file_level> only one production, no choice
  -1,
// At index 11 : <include_cpu_level> only one production, no choice
  -1,
//---- Added non terminal symbols from 'select' and 'repeat' instructions
// At index 12 : <select_goil_5F_syntax_0>
-1, // Choice 1
C_Lexique_goil_5F_lexique::kToken_include, -1, // Choice 2
C_Lexique_goil_5F_lexique::kToken_OIL_5F_VERSION, -1, // Choice 3
-1, // Choice 4
C_Lexique_goil_5F_lexique::kToken_CPU, -1, // Choice 5
  -1,
// At index 21 : <select_goil_5F_syntax_1>
C_Lexique_goil_5F_lexique::kToken__2D_, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken__2B_, -1, // Choice 2
C_Lexique_goil_5F_lexique::kToken_uint_5F_number, C_Lexique_goil_5F_lexique::kToken_float_5F_number, -1, // Choice 3
  -1,
// At index 29 : <select_goil_5F_syntax_2>
C_Lexique_goil_5F_lexique::kToken__3B_, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken__3A_, -1, // Choice 2
  -1,
// At index 34 : <select_goil_5F_syntax_3>
C_Lexique_goil_5F_lexique::kToken__7D_, C_Lexique_goil_5F_lexique::kToken_, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken_idf, -1, // Choice 2
C_Lexique_goil_5F_lexique::kToken_include, -1, // Choice 3
  -1,
// At index 42 : <select_goil_5F_syntax_4>
C_Lexique_goil_5F_lexique::kToken_TRUE, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken_FALSE, -1, // Choice 2
  -1,
// At index 47 : <select_goil_5F_syntax_5>
C_Lexique_goil_5F_lexique::kToken__7D_, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken_idf, -1, // Choice 2
  -1,
// At index 52 : <select_goil_5F_syntax_6>
C_Lexique_goil_5F_lexique::kToken_idf, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken__2D_, C_Lexique_goil_5F_lexique::kToken__2B_, C_Lexique_goil_5F_lexique::kToken_uint_5F_number, C_Lexique_goil_5F_lexique::kToken_float_5F_number, -1, // Choice 2
C_Lexique_goil_5F_lexique::kToken_TRUE, C_Lexique_goil_5F_lexique::kToken_FALSE, -1, // Choice 3
C_Lexique_goil_5F_lexique::kToken_string, -1, // Choice 4
  -1,
// At index 65 : <select_goil_5F_syntax_7>
C_Lexique_goil_5F_lexique::kToken__7B_, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken__3B_, -1, // Choice 2
  -1,
// At index 70 : <select_goil_5F_syntax_8>
C_Lexique_goil_5F_lexique::kToken_uint_5F_number, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken_float_5F_number, -1, // Choice 2
  -1,
// At index 75 : <select_goil_5F_syntax_9>
C_Lexique_goil_5F_lexique::kToken__7B_, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken__3B_, -1, // Choice 2
  -1,
// At index 80 : <select_goil_5F_syntax_10>
C_Lexique_goil_5F_lexique::kToken_g_5F_string, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken_string, -1, // Choice 2
  -1,
// At index 85 : <select_goil_5F_syntax_11>
C_Lexique_goil_5F_lexique::kToken_g_5F_string, -1, // Choice 1
C_Lexique_goil_5F_lexique::kToken_string, -1, // Choice 2
  -1,
// At index 90 : <> only one production, no choice
  -1,
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//       L L ( 1 )    D E C I S I O N    T A B L E S    I N D E X E S        *
//                                                                           *
//---------------------------------------------------------------------------*

static const PMSInt16 gDecisionIndexes [27] = {
0, // at 0 : <implementation_definition>
0, // at 1 : <start>
1, // at 2 : <file>
2, // at 3 : <sign>
3, // at 4 : <description>
4, // at 5 : <OIL_version>
5, // at 6 : <application_definition>
6, // at 7 : <object_definition_list>
7, // at 8 : <boolean>
8, // at 9 : <oil_declaration_list>
9, // at 10 : <oil_declaration>
10, // at 11 : <include_file_level>
11, // at 12 : <include_cpu_level>
12, // at 13 : <select_goil_5F_syntax_0>
21, // at 14 : <select_goil_5F_syntax_1>
29, // at 15 : <select_goil_5F_syntax_2>
34, // at 16 : <select_goil_5F_syntax_3>
42, // at 17 : <select_goil_5F_syntax_4>
47, // at 18 : <select_goil_5F_syntax_5>
52, // at 19 : <select_goil_5F_syntax_6>
65, // at 20 : <select_goil_5F_syntax_7>
70, // at 21 : <select_goil_5F_syntax_8>
75, // at 22 : <select_goil_5F_syntax_9>
80, // at 23 : <select_goil_5F_syntax_10>
85, // at 24 : <select_goil_5F_syntax_11>
90, // at 25 : <>
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//         'implementation_definition' non terminal implementation           *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_implementation_5F_definition_ (GALGAS_implementation & ,
                                C_Lexique_goil_5F_lexique * ) {
}

//---------------------------------------------------------------------------*
//                                                                           *
//                   'start' non terminal implementation                     *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_start_ (C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_start_i0_(inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                    'file' non terminal implementation                     *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_file_ (GALGAS_implementation & parameter_1,
                                GALGAS_applicationDefinition & parameter_2,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_file_i1_(parameter_1, parameter_2, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                    'sign' non terminal implementation                     *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_sign_ (GALGAS_bool & parameter_1,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_sign_i2_(parameter_1, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                'description' non terminal implementation                  *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_description_ (GALGAS_lstring & parameter_1,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_description_i3_(parameter_1, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                'OIL_version' non terminal implementation                  *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_OIL_5F_version_ (GALGAS_lstring & parameter_1,
                                GALGAS_lstring & parameter_2,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_OIL_5F_version_i4_(parameter_1, parameter_2, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//           'application_definition' non terminal implementation            *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_application_5F_definition_ (const GALGAS_implementation parameter_1,
                                GALGAS_applicationDefinition & parameter_2,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_application_5F_definition_i5_(parameter_1, parameter_2, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//           'object_definition_list' non terminal implementation            *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_object_5F_definition_5F_list_ (const GALGAS_implementation parameter_1,
                                GALGAS_objectsMap & parameter_2,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_object_5F_definition_5F_list_i6_(parameter_1, parameter_2, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                   Grammar start symbol implementation                     *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::_performSourceFileParsing_ (C_Compiler * inCompiler,
                                GALGAS_lstring inFilePath,
                                const GALGAS_implementation  parameter_1,
                                GALGAS_objectsMap &  parameter_2
                                COMMA_LOCATION_ARGS) {
  if (inFilePath.isValid ()) {
    const GALGAS_string filePathAsString = inFilePath.reader_string (HERE) ;
    C_String filePath = filePathAsString.stringValue () ;
    if (! filePath.isAbsolutePath ()) {
      filePath = inCompiler->sourceFilePath ().stringByDeletingLastPathComponent ().stringByAppendingPathComponent (filePath) ;
    }
    if (filePath.fileExists ()) {
    C_Lexique_goil_5F_lexique * scanner = NULL ;
    macroMyNew (scanner, C_Lexique_goil_5F_lexique (inCompiler, "", "", inCompiler->ioParametersPtr (), filePath COMMA_HERE)) ;
      if (scanner->sourceText () != NULL) {
        scanner->mPerformGeneration = inCompiler->mPerformGeneration ;
        const bool ok = scanner->performTopDownParsing (gProductions, gProductionNames, gProductionIndexes,
                                                        gFirstProductionIndexes, gDecision, gDecisionIndexes, 115) ;
        if (ok && ! scanner->mParseOnlyFlag) {
          cGrammar_goil_5F_cpu_5F_level_5F_include grammar ;
          grammar.nt_object_5F_definition_5F_list_ (parameter_1, parameter_2, scanner) ;
        }
      }else{
        C_String message ;
        message << "the '" << filePath << "' file exists, but cannot be read" ;
        const GALGAS_location errorLocation (inFilePath.reader_location (THERE)) ;
        inCompiler->semanticErrorAtLocation (errorLocation, message COMMA_THERE) ;
      }
    // }
    macroDetachSharedObject (scanner) ;
  }else{
    C_String message ;
    message << "the '" << filePath << "' file does not exist" ;
    const GALGAS_location errorLocation (inFilePath.reader_location (THERE)) ;
    inCompiler->semanticErrorAtLocation (errorLocation, message COMMA_THERE) ;
    }
  }
}

//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::_performSourceStringParsing_ (C_Compiler * inCompiler,
                                GALGAS_string inSourceString,
                                const GALGAS_implementation  parameter_1,
                                GALGAS_objectsMap &  parameter_2
                                COMMA_UNUSED_LOCATION_ARGS) {
  if (inSourceString.isValid ()) {
    const C_String sourceString = inSourceString.stringValue () ;
    C_Lexique_goil_5F_lexique * scanner = NULL ;
    macroMyNew (scanner, C_Lexique_goil_5F_lexique (inCompiler, inCompiler->ioParametersPtr (), sourceString, "Error when parsing dynamic string" COMMA_HERE)) ;
    scanner->mPerformGeneration = inCompiler->mPerformGeneration ;
    const bool ok = scanner->performTopDownParsing (gProductions, gProductionNames, gProductionIndexes,
                                                    gFirstProductionIndexes, gDecision, gDecisionIndexes, 115) ;
    if (ok && ! scanner->mParseOnlyFlag) {
      cGrammar_goil_5F_cpu_5F_level_5F_include grammar ;
      grammar.nt_object_5F_definition_5F_list_ (parameter_1, parameter_2, scanner) ;
    }
    macroDetachSharedObject (scanner) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//                  'boolean' non terminal implementation                    *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_boolean_ (GALGAS_lbool & parameter_1,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_boolean_i7_(parameter_1, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//            'oil_declaration_list' non terminal implementation             *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_oil_5F_declaration_5F_list_ (const GALGAS_implementationObjectMap parameter_1,
                                GALGAS_identifierMap & parameter_2,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_oil_5F_declaration_5F_list_i8_(parameter_1, parameter_2, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//              'oil_declaration' non terminal implementation                *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_oil_5F_declaration_ (const GALGAS_implementationObjectMap parameter_1,
                                GALGAS_identifierMap & parameter_2,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_oil_5F_declaration_i9_(parameter_1, parameter_2, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             'include_file_level' non terminal implementation              *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_include_5F_file_5F_level_ (GALGAS_implementation & parameter_1,
                                GALGAS_applicationDefinition & parameter_2,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_include_5F_file_5F_level_i10_(parameter_1, parameter_2, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             'include_cpu_level' non terminal implementation               *
//                                                                           *
//---------------------------------------------------------------------------*

void cGrammar_goil_5F_cpu_5F_level_5F_include::nt_include_5F_cpu_5F_level_ (const GALGAS_implementation parameter_1,
                                GALGAS_objectsMap & parameter_2,
                                C_Lexique_goil_5F_lexique * inLexique) {
  rule_goil_5F_syntax_include_5F_cpu_5F_level_i11_(parameter_1, parameter_2, inLexique) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_0' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_0 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_1' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_1 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_2' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_2 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_3' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_3 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_4' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_4 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_5' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_5 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_6' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_6 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_7' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_7 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_8' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_8 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_9' added non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_9 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_10' added non terminal implementation        *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_10 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//       'select_goil_5F_syntax_11' added non terminal implementation        *
//                                                                           *
//---------------------------------------------------------------------------*

PMSInt32 cGrammar_goil_5F_cpu_5F_level_5F_include::select_goil_5F_syntax_11 (C_Lexique_goil_5F_lexique * inLexique) {
  return inLexique->nextProductionIndex () ;
}

//---------------------------------------------------------------------------*

