#
# This makefile should be included into ARM subarchitecture
#

TEMP_SOURCE_DIRS += $(MACHINE_PATH)/..

SOURCES += tpl_machine_arm_generic.c \
tpl_irq.S \
tpl_system_call.S \
tpl_stacks.S \
tpl_trusted_fct.S \
tpl_vector_table.s

