#
# This makefile should be included into THUMB2 subarchitecture
#

TEMP_SOURCE_DIRS += $(MACHINE_PATH)/..

SOURCES += tpl_machine_arm_generic.c \
tpl_system_call.S \
tpl_ctx_switch.S \
tpl_memory_protection.c \
