#
# Trampoline OS
#
# Trampoline is copyright (c) IRCCyN 2005+
# Trampoline est protégé par la loi sur la propriété intellectuelle
#
# This software is distributed under the Lesser GNU Public Licence
#
# $Date$
# $Rev$
# $Author$
# $URL$
#
# Warning: This Makefile SHOULD not be called directly.
#          It is automatically called from the Makefile
#
# Trampoline OS
#
SOURCES += tpl_machine.c avr_switch_context.s tpl_dispatch.S

