#
# Trampoline OS
#
# Trampoline is copyright (c) IRCCyN 2005-2007
# Autosar extension is copyright (c) IRCCyN and ESEO 2007
# Trampoline est protégé par la loi sur la propriété intellectuelle
#
# This software is distributed under the Lesser GNU Public Licence
#
# $Date$
# $Rev$
# $Author$
# $URL$
#

#kernel AUTOSAR files
SOURCES += tpl_as_counter_kernel.c
SOURCES += tpl_as_st_kernel.c
SOURCES += tpl_as_isr_kernel.c
SOURCES += tpl_as_stack_monitor.c
SOURCES += tpl_as_timing_protec.c
SOURCES += tpl_as_action.c
SOURCES += tpl_as_counter.c
SOURCES += tpl_as_isr.c
SOURCES += tpl_as_protec_hook.c
SOURCES += tpl_as_schedtable.c
SOURCES += tpl_as_application.c
SOURCES += tpl_as_app_kernel.c
