// Generated by generate_test_data.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240521061119-gd6f36a96-dirty.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_2_int4_output_shift[5] = {-6, -8, -8, -7, -7};
