ECHO OFF
REM cbuild "test.Release+VHT_M0P.cprj"  
REM cbuild "test.Release+VHT_M23.cprj"  
REM cbuild "test.Release+VHT_M3.cprj" 
REM cbuild "test.Release+VHT_M4.cprj" 
REM cbuild "test.Release+VHT_M7.cprj"  
REM cbuild "test.Release+VHT_M7_UNROLLED.cprj"  
REM cbuild "test.Release+VHT_M33.cprj" 
cbuild "test.Release+VHT-Corstone-300.cprj" 
REM cbuild "test.Release+VHT-Corstone-310.cprj"  
REM cbuild "test.Release+FVP_M55.cprj" 
REM cbuild "test.Release+FVP_A5Neon.cprj"  
REM cbuild "test.Release+FVP_A7Neon.cprj"  
REM cbuild "test.Release+FVP_A9Neon.cprj"  
