#ifndef INPUT_H
#define INPUT_H

#include "tpl_os.h"
#include "../includes/fixedlib/fixed.h"

#define APP_Task_dnn_main_START_SEC_FRAM_UP_VAR_FRAM_UP_16BIT
#include "tpl_memmap.h"

VAR(fixed, AUTOMATIC) input[1][28][28] = {F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.435294151306),
                                      F_LIT(0.945098102093),
                                      F_LIT(1.0),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.647058844566),
                                      F_LIT(0.552941203117),
                                      F_LIT(0.552941203117),
                                      F_LIT(0.235294133425),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.77254909277),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.917647123337),
                                      F_LIT(0.51372551918),
                                      F_LIT(0.1254902035),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.172549024224),
                                      F_LIT(0.415686309338),
                                      F_LIT(0.611764729023),
                                      F_LIT(0.317647069693),
                                      F_LIT(0.313725501299),
                                      F_LIT(0.415686309338),
                                      F_LIT(0.658823549747),
                                      F_LIT(0.658823549747),
                                      F_LIT(0.917647123337),
                                      F_LIT(0.894117712975),
                                      F_LIT(0.298039227724),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.231372565031),
                                      F_LIT(0.941176533699),
                                      F_LIT(0.933333396912),
                                      F_LIT(0.149019613862),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.494117677212),
                                      F_LIT(0.996078491211),
                                      F_LIT(0.77254909277),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0509803965688),
                                      F_LIT(0.564705908298),
                                      F_LIT(0.95294123888),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.768627524376),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.149019613862),
                                      F_LIT(0.235294133425),
                                      F_LIT(0.819607913494),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.905882418156),
                                      F_LIT(0.168627455831),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0509803965688),
                                      F_LIT(0.443137288094),
                                      F_LIT(0.784313797951),
                                      F_LIT(0.929411828518),
                                      F_LIT(0.945098102093),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.490196108818),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.435294151306),
                                      F_LIT(0.749019622803),
                                      F_LIT(0.996078491211),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.996078491211),
                                      F_LIT(0.968627512455),
                                      F_LIT(0.968627512455),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.701960802078),
                                      F_LIT(0.0862745121121),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.77254909277),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.792156934738),
                                      F_LIT(0.329411774874),
                                      F_LIT(0.254901975393),
                                      F_LIT(0.258823543787),
                                      F_LIT(0.521568655968),
                                      F_LIT(0.894117712975),
                                      F_LIT(0.917647123337),
                                      F_LIT(0.321568638086),
                                      F_LIT(0.0274509824812),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.623529434204),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.658823549747),
                                      F_LIT(0.658823549747),
                                      F_LIT(0.313725501299),
                                      F_LIT(0.0235294140875),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.172549024224),
                                      F_LIT(0.658823549747),
                                      F_LIT(0.917647123337),
                                      F_LIT(0.454901993275),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0392156876624),
                                      F_LIT(0.109803929925),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.431372582912),
                                      F_LIT(0.894117712975),
                                      F_LIT(0.592156887054),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.447058856487),
                                      F_LIT(0.949019670486),
                                      F_LIT(0.235294133425),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.541176497936),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.768627524376),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.40784317255),
                                      F_LIT(0.964705944061),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.768627524376),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0509803965688),
                                      F_LIT(0.541176497936),
                                      F_LIT(0.964705944061),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.945098102093),
                                      F_LIT(0.231372565031),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0901960805058),
                                      F_LIT(0.0627451017499),
                                      F_LIT(0.113725498319),
                                      F_LIT(0.113725498319),
                                      F_LIT(0.458823561668),
                                      F_LIT(0.552941203117),
                                      F_LIT(0.800000071526),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.945098102093),
                                      F_LIT(0.592156887054),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.247058838606),
                                      F_LIT(0.917647123337),
                                      F_LIT(0.843137323856),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.8156863451),
                                      F_LIT(0.427451014519),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.321568638086),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.992156922817),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.956862807274),
                                      F_LIT(0.364705890417),
                                      F_LIT(0.0509803965688),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.1254902035),
                                      F_LIT(0.894117712975),
                                      F_LIT(0.988235354424),
                                      F_LIT(0.945098102093),
                                      F_LIT(0.54509806633),
                                      F_LIT(0.54509806633),
                                      F_LIT(0.54509806633),
                                      F_LIT(0.0980392247438),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0),
                                      F_LIT(0.0)};


#define APP_Task_dnn_main_STOP_SEC_FRAM_UP_VAR_FRAM_UP_16BIT
#include "tpl_memmap.h"

// __ro_hifram fixed input[1][28][28] = {F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.435294151306),
//                                       F_LIT(0.945098102093),
//                                       F_LIT(1.0),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.647058844566),
//                                       F_LIT(0.552941203117),
//                                       F_LIT(0.552941203117),
//                                       F_LIT(0.235294133425),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.77254909277),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.917647123337),
//                                       F_LIT(0.51372551918),
//                                       F_LIT(0.1254902035),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.172549024224),
//                                       F_LIT(0.415686309338),
//                                       F_LIT(0.611764729023),
//                                       F_LIT(0.317647069693),
//                                       F_LIT(0.313725501299),
//                                       F_LIT(0.415686309338),
//                                       F_LIT(0.658823549747),
//                                       F_LIT(0.658823549747),
//                                       F_LIT(0.917647123337),
//                                       F_LIT(0.894117712975),
//                                       F_LIT(0.298039227724),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.231372565031),
//                                       F_LIT(0.941176533699),
//                                       F_LIT(0.933333396912),
//                                       F_LIT(0.149019613862),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.494117677212),
//                                       F_LIT(0.996078491211),
//                                       F_LIT(0.77254909277),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0509803965688),
//                                       F_LIT(0.564705908298),
//                                       F_LIT(0.95294123888),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.768627524376),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.149019613862),
//                                       F_LIT(0.235294133425),
//                                       F_LIT(0.819607913494),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.905882418156),
//                                       F_LIT(0.168627455831),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0509803965688),
//                                       F_LIT(0.443137288094),
//                                       F_LIT(0.784313797951),
//                                       F_LIT(0.929411828518),
//                                       F_LIT(0.945098102093),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.490196108818),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.435294151306),
//                                       F_LIT(0.749019622803),
//                                       F_LIT(0.996078491211),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.996078491211),
//                                       F_LIT(0.968627512455),
//                                       F_LIT(0.968627512455),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.701960802078),
//                                       F_LIT(0.0862745121121),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.77254909277),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.792156934738),
//                                       F_LIT(0.329411774874),
//                                       F_LIT(0.254901975393),
//                                       F_LIT(0.258823543787),
//                                       F_LIT(0.521568655968),
//                                       F_LIT(0.894117712975),
//                                       F_LIT(0.917647123337),
//                                       F_LIT(0.321568638086),
//                                       F_LIT(0.0274509824812),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.623529434204),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.658823549747),
//                                       F_LIT(0.658823549747),
//                                       F_LIT(0.313725501299),
//                                       F_LIT(0.0235294140875),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.172549024224),
//                                       F_LIT(0.658823549747),
//                                       F_LIT(0.917647123337),
//                                       F_LIT(0.454901993275),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0392156876624),
//                                       F_LIT(0.109803929925),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.431372582912),
//                                       F_LIT(0.894117712975),
//                                       F_LIT(0.592156887054),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.447058856487),
//                                       F_LIT(0.949019670486),
//                                       F_LIT(0.235294133425),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.541176497936),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.768627524376),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.40784317255),
//                                       F_LIT(0.964705944061),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.768627524376),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0509803965688),
//                                       F_LIT(0.541176497936),
//                                       F_LIT(0.964705944061),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.945098102093),
//                                       F_LIT(0.231372565031),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0901960805058),
//                                       F_LIT(0.0627451017499),
//                                       F_LIT(0.113725498319),
//                                       F_LIT(0.113725498319),
//                                       F_LIT(0.458823561668),
//                                       F_LIT(0.552941203117),
//                                       F_LIT(0.800000071526),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.945098102093),
//                                       F_LIT(0.592156887054),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.247058838606),
//                                       F_LIT(0.917647123337),
//                                       F_LIT(0.843137323856),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.8156863451),
//                                       F_LIT(0.427451014519),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.321568638086),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.992156922817),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.956862807274),
//                                       F_LIT(0.364705890417),
//                                       F_LIT(0.0509803965688),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.1254902035),
//                                       F_LIT(0.894117712975),
//                                       F_LIT(0.988235354424),
//                                       F_LIT(0.945098102093),
//                                       F_LIT(0.54509806633),
//                                       F_LIT(0.54509806633),
//                                       F_LIT(0.54509806633),
//                                       F_LIT(0.0980392247438),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0),
//                                       F_LIT(0.0)};

#endif
