// Generated by generate_test_data.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240521061119-gd6f36a96-dirty.
#pragma once
#include <stdint.h>

const int32_t *const conv_out_activation_int4_input_bias = NULL;

const int32_t *const conv_out_activation_int4_biases = conv_out_activation_int4_input_bias;
