// Generated by generate_test_data.py using tensorflow version 2.16.1 (Keras version 2.16.0).
// Interpreter from tensorflow version 2.16.1 and revision v2.16.1-0-g5bc9d26649c.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_6_bias[4] = {2626786, 1816680, 3770128, 1468683};

const int32_t *const int16xint8xint32_6_biases = int16xint8xint32_6_bias;
