// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.5.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#define AVGPOOLING_4_BATCH_SIZE 3
#define AVGPOOLING_4_INPUT_N 1
#define AVGPOOLING_4_INPUT_W 1
#define AVGPOOLING_4_INPUT_H 20
#define AVGPOOLING_4_INPUT_C 2
#define AVGPOOLING_4_FILTER_W 1
#define AVGPOOLING_4_FILTER_H 3
#define AVGPOOLING_4_STRIDE_W 1
#define AVGPOOLING_4_STRIDE_H 3
#define AVGPOOLING_4_PAD SAME
#define AVGPOOLING_4_ACTIVATION_MAX 127
#define AVGPOOLING_4_ACTIVATION_MIN -128
#define AVGPOOLING_4_OUTPUT_C 2
#define AVGPOOLING_4_OUTPUT_W 1
#define AVGPOOLING_4_OUTPUT_H 7
#define AVGPOOLING_4_PADDING_H 0
#define AVGPOOLING_4_PADDING_W 0
