#
# Trampoline OS
#
# Trampoline is copyright (c) IRCCyN 2005+
# Trampoline est protege par la loi sur la propriete intellectuelle
#
# This software is distributed under the Lesser GNU Public Licence
#
# $Date$
# $Rev$
# $Author$
# $URL$
#

#kernel COM files
SOURCES += tpl_com_app_copy.c
SOURCES += tpl_com_filtering.c
SOURCES += tpl_com_filters.c
SOURCES += tpl_com_internal_com.c
SOURCES += tpl_com_external_com.c
SOURCES += tpl_com_notification.c
SOURCES += tpl_com_queue.c
SOURCES += tpl_com_message_management.c
