# listing of object files for Trick specific part
# TRICK_OBJS = _udivsi3.o _dvmd_tls.o
# listing of object files for OKI specific part
OKI_SOURCES = timer.c interruption.c i2c.c horloge.c gpio.c memoire.c interruption_vecteurs.s interruption_systeme.c uart.c 
# listing of object files for ARM generic part
ARM7_SOURCES = tpl_machine_arm7.c tpl_machine_arm7_asm.s tpl_startup_arm7.s


SOURCES += $(ARM7_SOURCES) $(OKI_SOURCES)
