// Generated by test_settings.py using tensorflow version 2.14.0 (Keras version 2.14.0).
// Interpreter from tensorflow version 2.14.0 and revision v2.14.0-rc1-21-g4dacf3f368e.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_int4_weights[18] =
    {-48, -39, 90, -13, -101, -91, 117, 77, -6, -35, 49, 27, 68, 14, -85, -18, 110, -15};
