// Generated by test_settings.py using tensorflow version 2.15.0 (Keras version 2.15.0).
// Interpreter from tflite_micro version 0.dev20231214171620-g47f77ab and revision None.
#pragma once
#include <stdint.h>

const int8_t lstm_2_input_to_cell_w[42] = {68,  111,  95, 35,  -39, 48,  -62, -74, -91, -28, -32, -13, -14, -92,
                                           -54, -121, -9, 2,   -70, 15,  66,  -6,  26,  -70, -52, -50, 67,  33,
                                           3,   57,   76, 127, 110, -70, 74,  -49, 35,  -42, 56,  -22, 13,  62};
