// Generated by generate_test_data.py using tensorflow version 2.10.0 (Keras version 2.10.0).
// Interpreter from tensorflow version 2.10.0 and revision upstream/v2.10.0-0-g359c3cdfc5f.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_weights[48] = {6,   18,  -76, 127,  -19, 68,  -36, -42,  35,   118, -93, -69,
                                         111, -51, -63, -79,  5,   15,  55,  -127, 26,   30,  -25, -116,
                                         0,   46,  27,  96,   -89, 116, 11,  42,   -69,  127, 14,  127,
                                         11,  -87, 83,  -126, -44, 16,  8,   81,   -116, -80, -2,  -127};
