// Generated by generate_test_data.py using tensorflow version 2.16.1 (Keras version 2.16.0).
// Interpreter from tensorflow version 2.16.1 and revision v2.16.1-0-g5bc9d26649c.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_2_output_multiplier[9] =
    {1896267360, 1894333615, 1893517140, 1893630191, 1894543342, 1894533248, 1895851048, 1896337119, 1891748709};

const int32_t *const int16xint8xint32_2_output_mult = int16xint8xint32_2_output_multiplier;
