//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'goil_routines.h'                           *
//                        Generated by version 2.0.0                         *
//                       july 7th, 2010, at 17h16'11"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef goil_routines_DEFINED
#define goil_routines_DEFINED

#include <string.h>

//---------------------------------------------------------------------------*

#include "galgas/GGS__header.h"

//---------------------------------------------------------------------------*

// Include imported semantics
#include "goil_basic_types.h"
#include "goil_options.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//                          Function 'projectName'                           *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_projectName ;

//---------------------------------------------------------------------------*

GGS_string function_projectName (C_Compiler & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                            Function 'oil_dir'                             *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_oil_dir ;

//---------------------------------------------------------------------------*

GGS_string function_oil_dir (C_Compiler & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                             Function 'arch'                               *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_arch ;

//---------------------------------------------------------------------------*

GGS_string function_arch (C_Compiler & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                             Function 'chip'                               *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_chip ;

//---------------------------------------------------------------------------*

GGS_string function_chip (C_Compiler & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                             Function 'board'                              *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_board ;

//---------------------------------------------------------------------------*

GGS_string function_board (C_Compiler & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                      Function 'add_path_component'                        *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_add_path_component ;

//---------------------------------------------------------------------------*

GGS_string function_add_path_component (C_Compiler &,
                                GGS_string ,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                    Function 'rootTemplatesDirectory'                      *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_rootTemplatesDirectory ;

//---------------------------------------------------------------------------*

GGS_string function_rootTemplatesDirectory (C_Compiler & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                      Function 'templates_directory'                       *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_templates_directory ;

//---------------------------------------------------------------------------*

GGS_string function_templates_directory (C_Compiler &,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                   Function 'template_string_if_exist'                     *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_template_string_if_exist ;

//---------------------------------------------------------------------------*

GGS_string function_template_string_if_exist (C_Compiler &,
                                GGS_string ,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                        Function 'template_string'                         *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_template_string ;

//---------------------------------------------------------------------------*

GGS_string function_template_string (C_Compiler &,
                                GGS_string ,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Function 'templateFilePath'                         *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_templateFilePath ;

//---------------------------------------------------------------------------*

GGS_string function_templateFilePath (C_Compiler &,
                                const GGS_string ,
                                const GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                     Function 'allTemplateFilePaths'                       *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_allTemplateFilePaths ;

//---------------------------------------------------------------------------*

GGS_stringlist  function_allTemplateFilePaths (C_Compiler &,
                                const GGS_string ,
                                const GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Function 'config_file'                           *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_config_file ;

//---------------------------------------------------------------------------*

GGS_lstring  function_config_file (C_Compiler & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Function 'extra_config_file'                        *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_extra_config_file ;

//---------------------------------------------------------------------------*

GGS_lstring  function_extra_config_file (C_Compiler & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                             Routine 'prefix'                              *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_prefix (C_Compiler &,
                                GGS_prefix_map  ,
                                GGS_string ,
                                GGS_string & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                         Routine 'performReplace'                          *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_performReplace (C_Compiler &,
                                GGS_prefix_map  ,
                                GGS_string ,
                                GGS_string ,
                                GGS_string & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                           Routine 'doReplace'                             *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_doReplace (C_Compiler &,
                                GGS_string &,
                                GGS_string ,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'do_replace_default'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_do_replace_default (C_Compiler &,
                                GGS_string &,
                                GGS_string ,
                                GGS_string ,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'replace_no_prefix'                         *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_replace_no_prefix (C_Compiler &,
                                GGS_prefix_map  ,
                                GGS_string ,
                                GGS_string ,
                                GGS_string & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                           Routine 'table_core'                            *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_table_core (C_Compiler &,
                                GGS_string ,
                                GGS_string ,
                                GGS_string ,
                                GGS_stringset  ,
                                GGS_string &,
                                GGS_string & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                        Routine 'add_to_stringset'                         *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_add_to_stringset (C_Compiler &,
                                GGS_stringset  &,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Routine 'file_in_path'                           *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_file_in_path (C_Compiler &,
                                GGS_lstring  & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'is_in_lstringlist'                         *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_is_in_lstringlist (C_Compiler &,
                                GGS_lstringlist  ,
                                GGS_lstring  ,
                                GGS_lstring  &,
                                GGS_bool & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                        Function 'isInLstringlist'                         *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_isInLstringlist ;

//---------------------------------------------------------------------------*

GGS_bool function_isInLstringlist (C_Compiler &,
                                GGS_lstringlist  ,
                                GGS_lstring   COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'add_lstring_unique'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_add_lstring_unique (C_Compiler &,
                                GGS_lstringlist  &,
                                GGS_lstring  ,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                      Routine 'set_lstring_if_empty'                       *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_set_lstring_if_empty (C_Compiler &,
                                GGS_lstring  &,
                                GGS_lstring  ,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                 Routine 'add_makefile_flag_if_not_empty'                  *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_add_makefile_flag_if_not_empty (C_Compiler &,
                                GGS_string &,
                                GGS_string ,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Function 'lstringWith'                           *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_lstringWith ;

//---------------------------------------------------------------------------*

GGS_lstring  function_lstringWith (C_Compiler &,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Function 'stripString'                           *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptorEX kFunction_descriptor_stripString ;

//---------------------------------------------------------------------------*

GGS_string function_stripString (C_Compiler &,
                                GGS_string  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                        Routine 'errorNoFileFound'                         *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_errorNoFileFound (C_Compiler &,
                                const GGS_stringlist  ,
                                const GGS_string ,
                                const GGS_lstring   COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*

#endif
