//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'include_number_set.h'                         *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     october 13th, 2006, at 16h32'15"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     abstract class 'cPtr_number_set'                      *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_number_set : public C_GGS_Object {
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

  public : cPtr_number_set (LOCATION_ARGS) ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

