//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'resources_verif.h'                          *
//                       Generated by version 1.9.10                         *
//                      april 9th, 2010, at 10h17'46"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef resources_verif_DEFINED
#define resources_verif_DEFINED

#include <string.h>

//---------------------------------------------------------------------------*

#include "galgas/GGS__header.h"

//---------------------------------------------------------------------------*

// Include imported semantics
#include "goil_types_resource.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//                     Routine 'resources_well_formed'                       *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_resources_well_formed (C_Compiler &,
                                const GGS_resource_map   COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                    Routine 'resolve_linked_resources'                     *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_resolve_linked_resources (C_Compiler &,
                                GGS_resource_map  & COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*

#endif
