//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'template_functions.h'                         *
//                        Generated by version 1.9.7                         *
//                     december 17th, 2009, at 9h52'7"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef template_functions_DEFINED
#define template_functions_DEFINED

#include <string.h>

//---------------------------------------------------------------------------*

#include "galgas/GGS__header.h"

//---------------------------------------------------------------------------*

// Include imported semantics
#include "system_config.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Class Predeclarations                            *
//                                                                           *
//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//                             Function 'tasks'                              *
//                                                                           *
//---------------------------------------------------------------------------*

extern const C_galgas_function_descriptor kFunction_descriptor_tasks ;

//---------------------------------------------------------------------------*

GGS_goilTemplateFieldMapList  function_tasks (C_Compiler &,
                                const GGS_systemConfig   COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*

#endif
