// Generated by generate_test_data.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240521061119-gd6f36a96-dirty.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_1_int4_output_multiplier[5] = {1279075283,
                                                                  1253149534,
                                                                  1686366600,
                                                                  1552250621,
                                                                  1977422534};

const int32_t *const kernel1x1_stride_x_y_1_int4_output_mult = kernel1x1_stride_x_y_1_int4_output_multiplier;
