//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'goil_options.h'                            *
//                Generated by version 1.3.1 (LL(1) grammar)                 *
//                       june 6th, 2006, at 11h54'13"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef goil_options_0_DEFINED
#define goil_options_0_DEFINED
#include "command_line_interface/AC_CLI_Options.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                  Command Line Options definitions class                   *
//                                                                           *
//---------------------------------------------------------------------------*

class goil_options : public AC_CLI_Options {
//--- Constructor
  public : goil_options (void) ;

//--- Boolean Command Line Interface Options
  public : virtual sint32 getBoolOptionsCount (void) const ;
  public : virtual bool getBoolOptionValue (const sint32 inIndex) const ;
  public : virtual void setBoolOptionValue (const sint32 inIndex, const bool inValue) ;
  public : virtual char getBoolOptionChar (const sint32 inIndex) const ;
  public : virtual const char * getBoolOptionString (const sint32 inIndex) const ;
  public : virtual const char * getBoolOptionDescription (const sint32 inIndex) const ;
  public : virtual bool boolOptionValueFromKeys (const char * inModuleName,
                                                    const char * inOptionName,
                                                    bool * outFound) const ;

//--- Unsigned integer Command Line Interface Options
  public : virtual sint32 getUintOptionsCount (void) const ;
  public : virtual uint32 getUintOptionValue (const sint32 inIndex) const ;
  public : virtual uint32 getUintOptionDefaultValue (const sint32 inIndex) const ;
  public : virtual void setUintOptionValue (const sint32 inIndex, const uint32 inValue) ;
  public : virtual char getUintOptionChar (const sint32 inIndex) const ;
  public : virtual const char * getUintOptionString (const sint32 inIndex) const ;
  public : virtual const char * getUintOptionDescription (const sint32 inIndex) const ;
  public : virtual uint32 uintOptionValueFromKeys (const char * inModuleName,
                                                      const char * inOptionName,
                                                      bool * outFound) const ;

//--- String Command Line Interface Options
  public : virtual sint32 getStringOptionsCount (void) const ;
  public : virtual C_String getStringOptionValue (const sint32 inIndex) const ;
  public : virtual void setStringOptionValue (const sint32 inIndex, const C_String & inValue) ;
  public : virtual char getStringOptionChar (const sint32 inIndex) const ;
  public : virtual const char * getStringOptionString (const sint32 inIndex) const ;
  public : virtual const char * getStringOptionDescription (const sint32 inIndex) const ;
  public : virtual C_String stringOptionValueFromKeys (const char * inModuleName,
                                                          const char * inOptionName,
                                                          bool * outFound) const ;

//--- Private arraies : current options values
  private : bool mBoolOptionValues [1] ;
  private : uint32 mUintOptionValues [1] ;
  private : C_String mStringOptionValues [1] ;
  private : TC_UniqueArray <C_String> mStringValue ;
} ;

//---------------------------------------------------------------------------*

#endif
