//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'goil_grammar.h'                            *
//             Generated by version version GALGAS_BETA_VERSION              *
//                    november 17th, 2010, at 19h29'55"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef GRAMMAR_goil_5F_grammar_HAS_BEEN_DEFINED
#define GRAMMAR_goil_5F_grammar_HAS_BEEN_DEFINED

//---------------------------------------------------------------------------*

#include "goil_syntax.h"
#include "goil_imp_def.h"
#include "goil_obj_os.h"
#include "goil_obj_task.h"
#include "goil_obj_counter.h"
#include "goil_obj_appmode.h"
#include "goil_obj_alarm.h"
#include "goil_obj_resource.h"
#include "goil_obj_event.h"
#include "goil_obj_isr.h"
#include "goil_obj_message.h"
#include "goil_obj_networkmessage.h"
#include "goil_obj_com.h"
#include "goil_obj_ipdu.h"
#include "goil_obj_scheduletable.h"
#include "goil_obj_application.h"
#include "goil_timing_prot_attrs.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*

class cGrammar_goil_5F_grammar : public cParser_goil_5F_syntax,
                                 public cParser_goil_5F_imp_5F_def,
                                 public cParser_goil_5F_obj_5F_os,
                                 public cParser_goil_5F_obj_5F_task,
                                 public cParser_goil_5F_obj_5F_counter,
                                 public cParser_goil_5F_obj_5F_appmode,
                                 public cParser_goil_5F_obj_5F_alarm,
                                 public cParser_goil_5F_obj_5F_resource,
                                 public cParser_goil_5F_obj_5F_event,
                                 public cParser_goil_5F_obj_5F_isr,
                                 public cParser_goil_5F_obj_5F_message,
                                 public cParser_goil_5F_obj_5F_networkmessage,
                                 public cParser_goil_5F_obj_5F_com,
                                 public cParser_goil_5F_obj_5F_ipdu,
                                 public cParser_goil_5F_obj_5F_scheduletable,
                                 public cParser_goil_5F_obj_5F_application,
                                 public cParser_goil_5F_timing_5F_prot_5F_attrs {
  public : virtual void nt_OIL_5F_version_ (GALGAS_lstring & outArgument0,
                                            GALGAS_lstring & outArgument1,
                                            C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_OIL_5F_version_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_alarm_ (GALGAS_alarm_5F_map & ioArgument0,
                                   C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_alarm_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_alarm_5F_action_5F_params_ (GALGAS_action_5F_obj & ioArgument0,
                                                       C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_alarm_5F_action_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_alarm_5F_autostart_5F_params_ (GALGAS_autostart_5F_obj & ioArgument0,
                                                          C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_alarm_5F_autostart_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_alarm_5F_parameters_ (GALGAS_lstring & ioArgument0,
                                                 GALGAS_action_5F_obj & ioArgument1,
                                                 GALGAS_autostart_5F_obj & ioArgument2,
                                                 GALGAS_lstringlist & ioArgument3,
                                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_alarm_5F_parameters_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_app_5F_attributes_ (GALGAS_app_5F_obj & ioArgument0,
                                               GALGAS_lstring inArgument1,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_app_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_appli_ (GALGAS_app_5F_map & ioArgument0,
                                   C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_appli_check_5F_appli_5F_exist (GALGAS_app_5F_map & ioArgument0,
                                                          GALGAS_bool & outArgument1,
                                                          C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_application_5F_definition_ (GALGAS_root_5F_obj & ioArgument0,
                                                       C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_application_5F_definition_check_5F_appli_5F_exist (GALGAS_root_5F_obj & ioArgument0,
                                                                              GALGAS_bool & outArgument1,
                                                                              C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_appmode_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_appmode_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_attribute_5F_name_ (GALGAS_lstring & outArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_attribute_5F_name_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_auto_5F_specifier_ (GALGAS_bool & outArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_auto_5F_specifier_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_bitordering_ (GALGAS_lstring & outArgument0,
                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_bitordering_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_bitposition_ (GALGAS_luint_36__34_ & outArgument0,
                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_bitposition_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_boolean_ (GALGAS_lbool & outArgument0,
                                     C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_boolean_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_cdatatype_ (GALGAS_lstring & outArgument0,
                                       C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_cdatatype_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_com_ (GALGAS_com & ioArgument0,
                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_com_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comappmode_ (GALGAS_lstringlist & ioArgument0,
                                        C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comappmode_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comerrorhook_ (GALGAS_basic_5F_type & ioArgument0,
                                          C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comerrorhook_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comstartcomextension_ (GALGAS_basic_5F_type & ioArgument0,
                                                  C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comstartcomextension_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comstatus_ (GALGAS_lstring & ioArgument0,
                                       C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comstatus_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comtimebase_ (GALGAS_basic_5F_type & ioArgument0,
                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comtimebase_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comusegetserviceid_ (GALGAS_basic_5F_type & ioArgument0,
                                                C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comusegetserviceid_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comuseparameteraccess_ (GALGAS_basic_5F_type & ioArgument0,
                                                   C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_comuseparameteraccess_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_counter_ (GALGAS_counter_5F_map & ioArgument0,
                                     C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_counter_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_counter_5F_parameters_ (GALGAS_basic_5F_type & ioArgument0,
                                                   GALGAS_basic_5F_type & ioArgument1,
                                                   GALGAS_basic_5F_type & ioArgument2,
                                                   GALGAS_lstring & ioArgument3,
                                                   GALGAS_lstringlist & ioArgument4,
                                                   GALGAS_counter_5F_type & ioArgument5,
                                                   GALGAS_lstring & ioArgument6,
                                                   C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_counter_5F_parameters_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_counter_5F_type_5F_attrs_ (GALGAS_counter_5F_type & outArgument0,
                                                      C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_counter_5F_type_5F_attrs_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_cpuordercallout_ (GALGAS_lstring & outArgument0,
                                             C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_cpuordercallout_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_datainterpretation_ (GALGAS_lstring & outArgument0,
                                                C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_datainterpretation_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_bool_ (GALGAS_bool_5F_class & outArgument0,
                                             C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_enum_ (GALGAS_basic_5F_type & outArgument0,
                                             C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_float_5F_number_ (GALGAS_float_5F_class & outArgument0,
                                                        C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_name_ (GALGAS_bool & outArgument0,
                                             GALGAS_lstring & outArgument1,
                                             C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_name_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_number_ (GALGAS_bool & outArgument0,
                                               GALGAS_luint_36__34_ & outArgument1,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_number_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_sint_33__32__5F_number_ (GALGAS_sint_33__32__5F_class & outArgument0,
                                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_sint_33__32__5F_number_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_sint_36__34__5F_number_ (GALGAS_sint_36__34__5F_class & outArgument0,
                                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_string_ (GALGAS_string_5F_class & outArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_uint_33__32__5F_number_ (GALGAS_uint_33__32__5F_class & outArgument0,
                                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_uint_33__32__5F_number_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_default_5F_uint_36__34__5F_number_ (GALGAS_uint_36__34__5F_class & outArgument0,
                                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_description_ (GALGAS_lstring & outArgument0,
                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_description_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_direct_5F_attributes_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_direct_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_direction_ (GALGAS_lstring & outArgument0,
                                       C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_direction_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_dynamic_5F_mp_ (GALGAS_base_5F_netprop & outArgument0,
                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_dynamic_5F_mp_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_enumeration_ (GALGAS_stringset & outArgument0,
                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_enumeration_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_enumerator_ (GALGAS_stringset & ioArgument0,
                                        C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_enumerator_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_event_ (GALGAS_event_5F_map & ioArgument0,
                                   C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_event_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_event_5F_attributes_ (GALGAS_event_5F_mask_5F_obj & ioArgument0,
                                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_event_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_file_ (GALGAS_implementation & ioArgument0,
                                  GALGAS_root_5F_obj & ioArgument1,
                                  C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_file_check_5F_appli_5F_exist (GALGAS_root_5F_obj & ioArgument0,
                                                         GALGAS_bool & outArgument1,
                                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_filter_ (GALGAS_filter_5F_prop_5F_obj & outArgument0,
                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_filter_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_firsttimeout_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_firsttimeout_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_float_5F_number_5F_set_ (GALGAS_float_5F_set & outArgument0,
                                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_free_5F_field_ (GALGAS_ident_5F_map & ioArgument0,
                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_free_5F_field_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_impl_5F_attr_5F_def_ (GALGAS_lstring & outArgument0,
                                                 GALGAS_imp_5F_type & outArgument1,
                                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_impl_5F_attr_5F_def_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_impl_5F_parameter_5F_list_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_impl_5F_parameter_5F_list_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_def_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_def_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_definition_ (GALGAS_implementation & ioArgument0,
                                                          C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_definition_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_list_ (GALGAS_string inArgument0,
                                                    GALGAS_implementation & ioArgument1,
                                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_list_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_spec_ (GALGAS_implementation & ioArgument0,
                                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_spec_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_spec_5F_list_ (GALGAS_implementation & ioArgument0,
                                                            C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_implementation_5F_spec_5F_list_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_include_5F_cpu_5F_level_ (GALGAS_os_5F_obj & ioArgument0,
                                                     GALGAS_com & ioArgument1,
                                                     GALGAS_task_5F_map & ioArgument2,
                                                     GALGAS_counter_5F_map & ioArgument3,
                                                     GALGAS_alarm_5F_map & ioArgument4,
                                                     GALGAS_resource_5F_map & ioArgument5,
                                                     GALGAS_event_5F_map & ioArgument6,
                                                     GALGAS_isr_5F_map & ioArgument7,
                                                     GALGAS_message_5F_map & ioArgument8,
                                                     GALGAS_netmess_5F_map & ioArgument9,
                                                     GALGAS_scheduletable_5F_map & ioArgument10,
                                                     GALGAS_app_5F_map & ioArgument11,
                                                     C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_include_5F_cpu_5F_level_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_include_5F_file_5F_level_ (GALGAS_implementation & ioArgument0,
                                                      GALGAS_root_5F_obj & ioArgument1,
                                                      C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_include_5F_file_5F_level_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_initialvalue_ (GALGAS_basic_5F_type & outArgument0,
                                          C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_initialvalue_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ipdu_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ipdu_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ipdu_5F_ref_ (GALGAS_lstring & ioArgument0,
                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ipdu_5F_ref_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ipducallout_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ipducallout_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ipduproperty_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ipduproperty_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_isr_ (GALGAS_isr_5F_map & ioArgument0,
                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_isr_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_isr_5F_attributes_ (GALGAS_basic_5F_type & ioArgument0,
                                               GALGAS_basic_5F_type & ioArgument1,
                                               GALGAS_lstringlist & ioArgument2,
                                               GALGAS_lstringlist & ioArgument3,
                                               GALGAS_lstringlist & ioArgument4,
                                               GALGAS_timing_5F_prot & ioArgument5,
                                               GALGAS_ident_5F_map & ioArgument6,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_isr_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_layerused_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_layerused_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_link_ (GALGAS_link_5F_obj & outArgument0,
                                  C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_link_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ltgt_5F_sync_5F_params_ (GALGAS_ltgt_5F_sync_5F_obj & outArgument0,
                                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ltgt_5F_sync_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_mask_5F_attribute_ (GALGAS_luint_36__34_ & outArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_mask_5F_attribute_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_mask_5F_x_5F_attribute_ (GALGAS_luint_36__34_ & outArgument0,
                                                    GALGAS_luint_36__34_ & outArgument1,
                                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_mask_5F_x_5F_attribute_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_maxsizeinbits_ (GALGAS_luint_36__34_ & outArgument0,
                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_maxsizeinbits_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_mess_ (GALGAS_message_5F_map & ioArgument0,
                                  C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_mess_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_message_5F_attributes_ (GALGAS_action_5F_obj & ioArgument0,
                                                   GALGAS_action_5F_obj & ioArgument1,
                                                   GALGAS_lstringlist & ioArgument2,
                                                   GALGAS_ident_5F_map & ioArgument3,
                                                   GALGAS_mess_5F_prop_5F_obj & ioArgument4,
                                                   C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_message_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_message_5F_property_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_message_5F_property_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_min_5F_max_5F_attribute_ (GALGAS_luint_36__34_ & outArgument0,
                                                     GALGAS_luint_36__34_ & outArgument1,
                                                     C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_min_5F_max_5F_attribute_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_minimumdelaytime_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_minimumdelaytime_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_mixed_5F_attributes_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_mixed_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_multiple_5F_specifier_ (GALGAS_bool & outArgument0,
                                                   C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_multiple_5F_specifier_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_net_5F_messageproperty_ (GALGAS_base_5F_netprop & ioArgument0,
                                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_net_5F_messageproperty_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_networkmess_ (GALGAS_netmess_5F_map & ioArgument0,
                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_networkmess_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_networkmessage_ (GALGAS_lstring & outArgument0,
                                            C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_networkmessage_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_networkordercallout_ (GALGAS_lstring & outArgument0,
                                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_networkordercallout_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_nm_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_nm_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_notification_5F_property_ (GALGAS_action_5F_obj & outArgument0,
                                                      C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_notification_5F_property_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_object_5F_definition_5F_list_ (GALGAS_os_5F_obj & ioArgument0,
                                                          GALGAS_com & ioArgument1,
                                                          GALGAS_task_5F_map & ioArgument2,
                                                          GALGAS_counter_5F_map & ioArgument3,
                                                          GALGAS_alarm_5F_map & ioArgument4,
                                                          GALGAS_resource_5F_map & ioArgument5,
                                                          GALGAS_event_5F_map & ioArgument6,
                                                          GALGAS_isr_5F_map & ioArgument7,
                                                          GALGAS_message_5F_map & ioArgument8,
                                                          GALGAS_netmess_5F_map & ioArgument9,
                                                          GALGAS_scheduletable_5F_map & ioArgument10,
                                                          GALGAS_app_5F_map & ioArgument11,
                                                          C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_object_5F_definition_5F_list_check_5F_appli_5F_exist (GALGAS_app_5F_map & ioArgument0,
                                                                                 GALGAS_bool & outArgument1,
                                                                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_os_ (GALGAS_os_5F_obj & ioArgument0,
                                C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_os_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_period_5F_offset_5F_attribute_ (GALGAS_luint_36__34_ & outArgument0,
                                                           GALGAS_luint_36__34_ & outArgument1,
                                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_period_5F_offset_5F_attribute_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_periodic_5F_attributes_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_periodic_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_queuesize_ (GALGAS_luint_36__34_ & outArgument0,
                                       C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_queuesize_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rde_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rde_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_received_5F_attributes_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_received_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_resource_ (GALGAS_resource_5F_map & ioArgument0,
                                      C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_resource_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_resource_5F_attributes_ (GALGAS_resource_5F_property_5F_obj & ioArgument0,
                                                    GALGAS_lstringlist & ioArgument1,
                                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_resource_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rqe_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rqe_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rqi_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rqi_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rue_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rue_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rui_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rui_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rze_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rze_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rzi_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rzi_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rzs_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_rzs_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_scheduletable_ (GALGAS_scheduletable_5F_map & ioArgument0,
                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_scheduletable_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_scheduletable_5F_parameters_ (GALGAS_scheduletable_5F_obj & ioArgument0,
                                                         GALGAS_lstring inArgument1,
                                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_scheduletable_5F_parameters_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sde_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sde_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sendingmessage_ (GALGAS_lstring & outArgument0,
                                            C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sendingmessage_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sent_5F_attributes_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sent_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_signed_5F_number_ (GALGAS_sint_36__34_ & outArgument0,
                                              C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_signed_5F_number_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sint_33__32__5F_number_5F_set_ (GALGAS_sint_33__32__5F_set & outArgument0,
                                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sint_33__32__5F_number_5F_set_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sint_36__34__5F_number_5F_set_ (GALGAS_sint_36__34__5F_set & outArgument0,
                                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sizeinbits_ (GALGAS_luint_36__34_ & outArgument0,
                                        C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sizeinbits_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sse_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sse_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ssi_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_ssi_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_action_5F_params_ (GALGAS_action_5F_list & ioArgument0,
                                                    C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_action_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_autostart_5F_abs_5F_params_ (GALGAS_autostart_5F_obj & outArgument0,
                                                              C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_autostart_5F_abs_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_autostart_5F_rel_5F_params_ (GALGAS_autostart_5F_obj & outArgument0,
                                                              C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_autostart_5F_rel_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_autostart_5F_sync_5F_params_ (GALGAS_autostart_5F_obj & outArgument0,
                                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_autostart_5F_sync_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_expiry_5F_pt_5F_params_ (GALGAS_lstring inArgument0,
                                                          GALGAS_expiry_5F_point_5F_obj & outArgument1,
                                                          C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_st_5F_expiry_5F_pt_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_start_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : static void _performSourceFileParsing_ (C_Compiler * inCompiler,
                                                   GALGAS_lstring inFileName
                                                   COMMA_LOCATION_ARGS) ;

  public : static void _performSourceStringParsing_ (C_Compiler * inCompiler,
                                                     GALGAS_string inSourceString
                                                     COMMA_LOCATION_ARGS) ;

  public : virtual void nt_static_5F_mp_ (GALGAS_base_5F_netprop & outArgument0,
                                          C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_static_5F_mp_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sze_5F_attributes_ (GALGAS_mess_5F_prop_5F_obj & ioArgument0,
                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_sze_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_task_ (GALGAS_task_5F_map & ioArgument0,
                                  C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_task_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_task_5F_attributes_ (GALGAS_basic_5F_type & ioArgument0,
                                                GALGAS_lstring & ioArgument1,
                                                GALGAS_basic_5F_type & ioArgument2,
                                                GALGAS_task_5F_autostart_5F_obj & ioArgument3,
                                                GALGAS_lstringlist & ioArgument4,
                                                GALGAS_lstringlist & ioArgument5,
                                                GALGAS_lstringlist & ioArgument6,
                                                GALGAS_lstringlist & ioArgument7,
                                                GALGAS_timing_5F_prot & ioArgument8,
                                                GALGAS_ident_5F_map & ioArgument9,
                                                C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_task_5F_attributes_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_task_5F_autostart_5F_params_ (GALGAS_task_5F_autostart_5F_obj & outArgument0,
                                                         C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_task_5F_autostart_5F_params_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_timeoffset_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_timeoffset_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_timeout_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_timeout_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_timeperiod_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_timeperiod_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_timing_5F_prot_5F_attrs_ (GALGAS_basic_5F_type & outArgument0,
                                                     GALGAS_basic_5F_type & outArgument1,
                                                     GALGAS_basic_5F_type & outArgument2,
                                                     GALGAS_basic_5F_type & outArgument3,
                                                     GALGAS_basic_5F_type & outArgument4,
                                                     GALGAS_rezlock_5F_map & outArgument5,
                                                     C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_timing_5F_prot_5F_attrs_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_transferproperty_ (GALGAS_lstring & outArgument0,
                                              C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_transferproperty_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_transmissionmode_ (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_transmissionmode_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_trusted_5F_fcts_ (GALGAS_app_5F_trusted_5F_obj & outArgument0,
                                             C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_trusted_5F_fcts_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_uint_33__32__5F_attribute_5F_name_ (GALGAS_lstring & outArgument0,
                                                               C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_uint_33__32__5F_attribute_5F_name_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_uint_33__32__5F_number_5F_set_ (GALGAS_uint_33__32__5F_set & outArgument0,
                                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_uint_33__32__5F_number_5F_set_parse (C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_uint_36__34__5F_number_5F_set_ (GALGAS_uint_36__34__5F_set & outArgument0,
                                                           C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_use_ (GALGAS_lstringlist & ioArgument0,
                                 C_Lexique_goil_5F_lexique * inCompiler) ;

  public : virtual void nt_use_parse (C_Lexique_goil_5F_lexique * inCompiler) ;


  public : virtual PMSInt32 select_goil_5F_syntax_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_syntax_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_syntax_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_syntax_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_syntax_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_syntax_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_syntax_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_7 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_8 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_9 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_10 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_11 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_12 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_13 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_14 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_15 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_16 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_17 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_18 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_19 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_20 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_21 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_22 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_23 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_24 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_25 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_imp_5F_def_26 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_7 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_os_8 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_task_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_task_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_task_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_task_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_task_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_counter_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_counter_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_counter_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_counter_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_counter_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_counter_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_counter_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_counter_7 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_appmode_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_alarm_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_alarm_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_alarm_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_alarm_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_alarm_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_alarm_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_resource_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_resource_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_event_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_event_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_isr_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_isr_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_7 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_8 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_9 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_10 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_11 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_12 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_13 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_14 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_15 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_16 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_17 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_18 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_19 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_20 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_message_21 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_networkmessage_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_networkmessage_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_networkmessage_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_networkmessage_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_networkmessage_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_networkmessage_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_networkmessage_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_networkmessage_7 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_com_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_com_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_ipdu_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_ipdu_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_ipdu_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_ipdu_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_ipdu_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_ipdu_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_ipdu_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_ipdu_7 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_7 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_8 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_9 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_10 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_11 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_12 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_scheduletable_13 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_1 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_2 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_3 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_4 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_5 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_6 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_7 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_obj_5F_application_8 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_timing_5F_prot_5F_attrs_0 (C_Lexique_goil_5F_lexique *) ;

  public : virtual PMSInt32 select_goil_5F_timing_5F_prot_5F_attrs_1 (C_Lexique_goil_5F_lexique *) ;
} ;

//---------------------------------------------------------------------------*

#endif
