//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'goil_check.h'                             *
//                    Generated by version version 2.1.4                     *
//                     january 10th, 2011, at 14h31'40"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef goil_check_ENTITIES_DEFINED
#define goil_check_ENTITIES_DEFINED

//---------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------*

#include "goil_semantic_types.h"
#include "goil_basic_types.h"
#include "goil_types_action.h"
#include "goil_routines.h"

//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'check_uint32_range'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_check_5F_uint_33__32__5F_range (GALGAS_uint_33__32__5F_set inArgument0,
                                             GALGAS_location inArgument1,
                                             GALGAS_uint inArgument2,
                                             C_Compiler * inCompiler
                                             COMMA_LOCATION_ARGS) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

#endif
