//---------------------------------------------------------------------------*
//                                                                           *
//                        File 'include_uint_list.h'                         *
//             Generated by version 1.4.6 (SLR grammar) [debug]              *
//                     october 19th, 2006, at 11h11'57"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                          class 'cPtr_uint_list'                           *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_uint_list : public cPtr_number_set {
  private : typedef cPtr_number_set inherited ;
//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

  public : cPtr_uint_list (const GGS_number_list &  COMMA_LOCATION_ARGS) ;
  public : GGS_number_list  numbers ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

