// Generated by generate_test_data.py using flatc version 23.5.26
// Interpreter from tflite_micro runtime version 0.dev20240521061119-gd6f36a96-dirty.
#pragma once
#include <stdint.h>

const int8_t basic_int4_output[20] = {-19, -6,  -17, -9,  -9,  -16, -12, -15, -9,  -10,
                                      -21, -18, -15, -11, -11, -8,  -5,  -16, -16, -22};

const int8_t *const basic_int4_output_ref = basic_int4_output;
